/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0/samples
 */

plugins {
  id("java-library")
  id("com.github.johnrengelman.shadow") version "7.0.0"
  id("com.github.sherter.google-java-format") version "0.9"
}

group = "com.github.jhorology.bitwig"
version = "0.1.0-SNAPSHOT"

repositories {
  mavenCentral()
  maven {
    url = uri("https://maven.bitwig.com")
  }
}

dependencies {
  // provided
  implementation("com.bitwig:extension-api:13") // provided
  implementation("org.apache.commons:commons-lang3:3.5")

  implementation("org.slf4j:slf4j-api:1.7.30")

  // development build
  if (hasProperty("dev")) {
    implementation("ch.qos.logback:logback-core:1.2.3")
  }
}

defaultTasks("shadowJar")

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
  archiveFileName.set("XoneK2.bwextension")
  dependencies {
    // exclude provided dependencies
    exclude(dependency("com.bitwig:extension-api:13"))
    exclude(dependency("org.apache.commons:commons-lang3:3.5"))
  }
}

tasks.register<Copy>("installBwExtension") {
  dependsOn("clean", "shadowJar")
  from("build/libs") {
    include("*.bwextension")
  }
  // TODO platform specific
  into("${System.getProperty("user.home")}/Documents/Bitwig Studio/Extensions")
}

// for debugging on console:
//   gradle -Pdev start
tasks.register<Exec>("start") {
  dependsOn("installBwExtension")
  // TODO platform specific
  commandLine("/Applications/Bitwig Studio.app/Contents/MacOS/BitwigStudio")
  if (hasProperty("dev")) {
    environment("BITWIG_DEBUG_PORT", 8989)
  }
}
